### ISSUE TITLE
can not download the data

### ISSUE THREAD

**Issue by jeannotes** [nihalsid/stylegan2-ada-3d-texture#1]
hi. great work, but now we cannot download "photoshape-data.zip" with the link you provided.
hope that you can fix that

**Comment by easonnie** [comment]
I'm having same issue.

**Comment by nihalsid** [comment]
hi, I updated the link. Download should work now.

**Comment by jeannotes** [comment]
hi， any difference between this repo of stylegan2 with Texturify?
