### ISSUE TITLE
shapenet-chairs-manifold-highres_stat.pt

### ISSUE THREAD

**Issue by porcofly** [nihalsid/stylegan2-ada-3d-texture#8]
Hello, the Example training you gave seems to still require this file: shapenet-chairs-manifold-highres_stat.pt. What file is this and where can I get it? Looking forward to your answer very much

**Comment by nihalsid** [comment]
Hi, sorry for the late response. Here's the link to it: https://drive.google.com/file/d/1V6Kic2T1W9EKGsc205S5oCdpptIMK15N/view?usp=sharing

I dont remember if this is actually used tho
